apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: cert-manager-monitor
  namespace: cert-manager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
