apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      serviceAccountName: pod-service-account
      imagePullSecrets:
        - name: docker-login-secret
      containers:
      - name: webapp
        image: csye712504/api-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: database-service.webapp.svc.cluster.local
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: DB_NAME
        - name: STORAGE_BUCKET_NAME
          value: your-bucket-name-001
        - name : GOOGLE_PROJECT_ID
          value: gcp-dev-7125
      initContainers:
      - name: flyway-init-container
        image: csye712504/flyway:latest
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: database-service.webapp.svc.cluster.local
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: DB_NAME
        - name: DB_SCHEMA
          valueFrom:
            configMapKeyRef:
              name: webapp-config
              key: DB_SCHEMA

        
      
