apiVersion: v1
kind: Secret
metadata:
    name: docker-login-secret
    namespace: webapp
data:
    .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJjc3llNzEyNUBnbWFpbC5jb20iLCJwYXNzd29yZCI6ImRja3JfcGF0X1ZXcHU2ampEbGhwc2JlWjVkaTdxcmhqSUxpUSIsImVtYWlsIjoiY3N5ZTcxMjVAZ21haWwuY29tIiwiYXV0aCI6IlkzTjVaVGN4TWpWQVoyMWhhV3d1WTI5dE9tUmphM0pmY0dGMFgxWlhjSFUyYW1wRWJHaHdjMkpsV2pWa2FUZHhjbWhxU1V4cFVRPT0ifX19
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
    name: database-secrets
    namespace: webapp
type: Opaque
data:
    DB_USERNAME: cm9vdA==
    DB_PASSWORD: ZGF0YWJhc2U=
