apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.dockerSecret.name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.dockerSecret.data.dockerconfigjson }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.databaseSecret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.databaseSecret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
