apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $value := .Values.serviceAccount.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.database.name }}-sa"
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false
