apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.webapp.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.services.webapp.type }}
  ports:
  - port: {{ .Values.services.webapp.port }}
    targetPort: {{ .Values.services.webapp.targetPort }}
    protocol: TCP
  selector:
    app: {{ .Values.services.webapp.selector.app }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.database.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.services.database.selector.app }}
  clusterIP: {{ .Values.services.database.clusterIP }}
  ports:
  - port: {{ .Values.services.database.port }}
    targetPort: {{ .Values.services.database.targetPort }}
