apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClasses.gcp.name }}
provisioner: {{ .Values.storageClasses.gcp.provisioner }}
reclaimPolicy: {{ .Values.storageClasses.gcp.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClasses.gcp.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storageClasses.gcp.allowVolumeExpansion }}
