apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webapp-virtualservice
  namespace: webapp
spec:
  hosts:
  - "*"  # or use dev.gcp.csye7125.xyz
  gateways:
  - webapp-gateway
  http:
  - match:
    - uri:
        prefix: /dashboard
    route:
    - destination:
        host: streamlit-service.webapp.svc.cluster.local
        port:
          number: 80 # 8501

  - match:
    - uri:
        prefix: "/"  # Catches everything else
    route:
    - destination:
        host: webapp-service.webapp.svc.cluster.local
        port:
          number: 8080
